### ISSUE TITLE
asyncSerialForEach is a special case of asyncParallelForEach

### ISSUE THREAD

**Issue by alfredosalzillo** [jfet97/asynchronousforeach#5]
Why is not asyncSerialForEach implemented as a special case of asyncParallelForEach?
An asyncSerialForEach is an asyncParallelForEach with concurrent number of esecution = 1, or i'm missing something?
Can't it be implemented like this?
```javascript
Array.prototype[asyncSerialForEach] = function (callback, thisArgs) {
  return this[asyncParallelForEach](callback, 1, thisArgs);
} 
```

**Comment by jfet97** [comment]
The current implementation of `Array.prototype[asyncSerialForEach]` is faster
